<a href="https://colab.research.google.com/github/Akash431299/Maths-identify/blob/main/Maths_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=0
for i in range(5):
 a=i
 print (a)

0
1
2
3
4


In [ ]:

i=0
while i<10:
    if(i%2==0):
       print(i)
    i+=1

0
2
4
6
8


In [17]:

# Create two arrays# Create two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Add arrays (element-wise)
result = arr1 + arr2
print(result)  # [6 8 10 12]

# Calculate statistics
print("Mean:", np.mean(arr1))
print("Sum:", np.sum(arr1))
print("Max:", np.max(arr1))


arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Add arrays (element-wise)
result = arr1 + arr2
print(result)  # [6 8 10 12]

# Calculate statistics
print("Mean:", np.mean(arr1))
print("Sum:", np.sum(arr1))
print("Max:", np.max(arr1))

# Create two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Add arrays (element-wise)
result = arr1 + arr2
print(result)  # [6 8 10 12]

# Calculate statistics
print("Mean:", np.mean(arr1))
print("Sum:", np.sum(arr1))
print("Max:", np.max(arr1))

NameError: name 'np' is not defined

In [ ]:

# Create two arrays# Create two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Add arrays (element-wise)
result = arr1 + arr2
print(result)  # [6 8 10 12]

# Calculate statistics
print("Mean:", np.mean(arr1))
print("Sum:", np.sum(arr1))
print("Max:", np.max(arr1))


arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Add arrays (element-wise)
result = arr1 + arr2
print(result)  # [6 8 10 12]

# Calculate statistics
print("Mean:", np.mean(arr1))
print("Sum:", np.sum(arr1))
print("Max:", np.max(arr1))

# Create two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Add arrays (element-wise)
result = arr1 + arr2
print(result)  # [6 8 10 12]

# Calculate statistics
print("Mean:", np.mean(arr1))
print("Sum:", np.sum(arr1))
print("Max:", np.max(arr1))

In [19]:
pip install numpy

In [20]:
import numpy as np

In [21]:

# Create two arrays# Create two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Add arrays (element-wise)
result = arr1 + arr2
print(result)  # [6 8 10 12]

# Calculate statistics
print("Mean:", np.mean(arr1))
print("Sum:", np.sum(arr1))
print("Max:", np.max(arr1))


arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Add arrays (element-wise)
result = arr1 + arr2
print(result)  # [6 8 10 12]

# Calculate statistics
print("Mean:", np.mean(arr1))
print("Sum:", np.sum(arr1))
print("Max:", np.max(arr1))

# Create two arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Add arrays (element-wise)
result = arr1 + arr2
print(result)  # [6 8 10 12]

# Calculate statistics
print("Mean:", np.mean(arr1))
print("Sum:", np.sum(arr1))
print("Max:", np.max(arr1))

[ 6  8 10 12]
Mean: 2.5
Sum: 10
Max: 4
[ 6  8 10 12]
Mean: 2.5
Sum: 10
Max: 4
[ 6  8 10 12]
Mean: 2.5
Sum: 10
Max: 4
